---
sudo: required
language: python
python:
  #- "3.6"
  #- "3.7"
  - "3.8"
  
services:
  - docker

env:
  jobs:
    - TOX_DISTRO=centos8           TOX_ANSIBLE=latest
    - TOX_DISTRO=centos7           TOX_ANSIBLE=latest
    - TOX_DISTRO=centos6           TOX_ANSIBLE=latest
    - TOX_DISTRO=debian10          TOX_ANSIBLE=latest
    - TOX_DISTRO=debian9           TOX_ANSIBLE=latest
    - TOX_DISTRO=debian8           TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora32          TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora31          TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora30          TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu2004        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1804        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1604        TOX_ANSIBLE=latest
    - TOX_DISTRO=centos8           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centos7           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centos6           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian10          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian9           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian8           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora32          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora31          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora30          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu2004        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1804        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1604        TOX_ANSIBLE={29,28}



cache:
  pip: true
  directories:
  - ".tox"

install:
  - python3 -m pip install tox-travis

  # Check tox version
  - tox --version

  # Check installed tox
  - pip freeze | grep tox

script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .)-ansible${TOX_ANSIBLE}-${TOX_DISTRO}
  - |
    rm -r .tox/py*/log/*
    find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
