---
sudo: required
language: python
python:
  #- "3.6"
  #- "3.7"
  - "3.8"
  
services:
  - docker

addons:
  apt:
    packages:
      - python3-pip

install:
  - python3 -m pip install tox-travis

  # Check tox-travis version
  - tox-travis --version

  # Check installed tox-travis
  - pip freeze | grep tox-travis

script:
  - tox-travis -l
  - tox-travis
